Add UA based rewrites example
vercel/examples pull request #195
Opened 2022-03-18 19:22 UTC by goncy

This example shows how to load a different page based on users UA

![image](https://user-images.githubusercontent.com/6494462/159069680-97490c22-9d4b-4a7a-9066-2a1dc3b58671.png)

2022-03-18 19:32 UTC, gbibeaul approved these changes
Tiny request and language corrections

2022-03-18 19:32 UTC, gbibeaul commented on edge-functions/ua-based-app/components/Home.tsx
> +          We will rewrite our user to different pages based on its UA so we have
Maybe adding a link to a UA description could help educate people who are unfamiliar with the concept.

2022-03-18 19:46 UTC, lfades requested changes
The example should have a more clear name, like: `user-agent-based-rendering`, or `render-different-viewport-for-user-agent`. Whatever makes more sense but that is clear enough

2022-03-18 19:46 UTC, lfades commented on edge-functions/ua-based-app/pages/_middleware.ts
> +
We should also check for public files

2022-03-18 19:46 UTC, lfades commented on edge-functions/ua-based-app/public/UA example - Implementation (1).jpg:Zone.Identifier
> +HostUrl=about:internet
What are these?

2022-03-18 19:46 UTC, lfades commented on edge-functions/ua-based-app/public/UA example - Implementation (2) (1).jpg:Zone.Identifier
> +HostUrl=about:internet
What are these?

2022-03-18 19:46 UTC, lfades commented on edge-functions/ua-based-app/README.md
> +# ua-based-app example
```suggestion 
# User Agent Based Rendering
```

2022-03-18 19:47 UTC, goncy commented on edge-functions/ua-based-app/public/UA example - Implementation (1).jpg:Zone.Identifier
> +HostUrl=about:internet
Ah, probably squoosh generated those

2022-03-19 00:41 UTC, lfades approved these changes
Added some changes:

- The 404 now renders the 404 page
- The public files check now is an empty return, returning the request is no good
- Changed the contents of the main page to be about explaining what's the example about instead of giving a tutorial

2022-03-19 15:11 UTC, merged