Add news demo
vercel/examples pull request #25
Opened 2021-10-29 20:03 UTC by goncy

Adds [this demo](https://next-news.vercel.app) to the list

2021-10-29 23:28 UTC, lfades commented on edge-functions/next-news/README.md
> +https://edge-next-news.vercel.app
This is the same prefix other examples are using

```suggestion
https://edge-functions-next-news.vercel.app
```

2021-10-29 23:29 UTC, lfades commented on edge-functions/next-news/README.md
> +```
The naming here should change to `next-news` from `edge-next-news`

2021-10-29 23:30 UTC, lfades commented on edge-functions/next-news/components/header.tsx
> +export default () => (
Let's export named components, Next.js should be complaining about this in the console.

2021-10-29 23:31 UTC, lfades commented on edge-functions/next-news/pages/_middleware.ts
> +}
This part should be included on the readme, alongside a description of why are we using middleware in this example.

2021-10-29 23:31 UTC, lfades requested changes
Added some comments

2021-10-30 00:09 UTC, leerob commented on edge-functions/next-news/README.md
> +# Hacker Next
```suggestion
# Next News
```

2021-10-30 01:43 UTC, lfades commented on edge-functions/next-news/.gitignore
> +.output
Let's use the .gitignore of our other examples here.

2021-10-30 16:04 UTC, lfades commented on edge-functions/next-news/README.md
> +This is an example showing a hacker news clone using Next.js with edge functions
````suggestion

This is an example showing a hacker news clone using Next.js. Edge functions are used to show how a rewrite from `/` to `/news/1` works. Below is the code from [pages/\_middleware.ts](pages/_middleware.ts):

```ts
import { NextResponse as Response } from "next/server";

export default function middleware(req) {
  if (req.nextUrl.pathname === "/") {
    return Response.rewrite("/news/1");
  }
}
```
````

2021-10-30 16:05 UTC, lfades commented on edge-functions/next-news/README.md
> +
```suggestion
```

2021-10-30 16:05 UTC, lfades approved these changes
LGTM!

2021-10-31 15:21 UTC, merged