New Example: Streams
vercel/examples pull request #375
Opened 2022-08-16 12:32 UTC by okbel

### Description

This example shows how to use Streams with Vercel Edge Functions 

### Demo URL

https://edge-streams.vercel.app

### Type of Change

- [X] New Example
- [ ] Example updates (Bug fixes, new features, etc.)
- [ ] Other (changes to the codebase, but not to examples)

### New Example Checklist

- [ ] 🛫 `npm run new-example` was used to create the example
- [ ] 📚 The template wasn't used but I carefuly read the [Adding a new example](https://github.com/vercel/examples#adding-a-new-example) steps and implemented them in the example
- [ ] 📱 Is it responsive? Are mobile and tablets considered?

2022-08-18 02:03 UTC, lfades requested changes
Added some minor misc changes and it looks good to me!

Renaming the example to `streaming` can make it easier to understand, and I also propose the following renames to the files in `pages/api` for more clarity:

- `/01-readable-stream.ts`
- `/02-transform-stream.ts`
- `/03-transform-stream-external`

I'll be requesting changes for now only until we know it works perfectly well and it doesn't get merged by accident.

2022-10-12 14:51 UTC, okbel commented
@Schniz can you take a quick 👁️ at this? Main focus to pages/api/*

2022-10-12 15:12 UTC, goncy commented on edge-functions/streams/package.json
> +  "private": true,
Should we add a name to it to prevent the turborepo error?

2022-10-17 11:29 UTC, dominiksipowicz approved these changes

2022-10-20 18:28 UTC, merged