Reconciles Edge Middleware and Edge Functions examples
vercel/examples pull request #532
Opened 2023-01-25 21:20 UTC by manovotny

### Description

### Demo URL

### Type of Change

- [ ] New Example
- [ ] Example updates (Bug fixes, new features, etc.)
- [ ] Other (changes to the codebase, but not to examples)

### New Example Checklist

- [ ] 🛫 `npm run new-example` was used to create the example
- [ ] 📚 The template wasn't used but I carefuly read the [Adding a new example](https://github.com/vercel/examples#adding-a-new-example) steps and implemented them in the example
- [ ] 📱 Is it responsive? Are mobile and tablets considered?

2023-01-27 22:05 UTC, leerob commented
Okay, I believe all Vercel projects have the correct root directory updated!

2023-01-30 21:53 UTC, leerob approved these changes

2023-01-31 15:30 UTC, lfades requested changes
Blocking temporarily.

We need to disable the publishing action in this PR or the Templates Marketplace is gonna go brrrrrrr

2023-01-31 16:25 UTC, lfades approved these changes
LGTM! 🚢 🚀

2023-01-31 17:07 UTC, merged