Add examples for flags with Toolbar
vercel/examples pull request #878
Opened 2024-03-05 16:34 UTC by AndyBitz

### Description

Adds examples for LauchDarkly, Optimizely, Split, and Statsig to be used with the Toolbar.

### Demo URL

See all attached Toolbar Flags deployments.

### Type of Change

- [x] New Example
- [ ] Example updates (Bug fixes, new features, etc.)
- [ ] Other (changes to the codebase, but not to examples)

2024-03-05 16:44 UTC, dferber90 requested changes
<picture data-single-emoji=":excited:" title=":excited:"><img class="emoji" width="20" height="auto" src="https://emoji.slack-edge.com/T0CAQ00TU/excited/4a2b1dbeddb46e42.gif" alt=":excited:" align="absmiddle"></picture>

2024-03-05 16:44 UTC, dferber90 commented on toolbar-flags/launchdarkly-starter/app/.well-known/vercel/flags/route.ts
> +    environment: "production",
these could be env vars

2024-03-05 16:44 UTC, dferber90 commented on toolbar-flags/launchdarkly-starter/app/page.tsx
> +"use server";
this should be removed, i added it accidentally

2024-03-05 16:44 UTC, dferber90 commented on toolbar-flags/launchdarkly-starter/app/page.tsx
> +  registerFlagValues(flags);
let's remove this part

2024-03-05 16:44 UTC, dferber90 commented on toolbar-flags/split-starter/app/layout.tsx
> +          <meta name="vercel-flags-plaintext-overrides" />
let's remove this comment as we're now advocating for `overrideEncryptionMode`

2024-03-05 16:44 UTC, dferber90 commented on toolbar-flags/split-starter/app/page.tsx
> +  registerFlagValues(flags);
let's delete

2024-03-05 16:44 UTC, dferber90 commented on toolbar-flags/optimizely-starter/app/page.tsx
> +  registerFlagValues(flags);
let's remove

2024-03-05 16:44 UTC, dferber90 commented on toolbar-flags/statsig-starter/app/page.tsx
> +  registerFlagValues(flags);
let's remove

2024-03-06 13:28 UTC, leerob approved these changes
You might want the versions for `next` at `latest`, but not blocking!

2024-03-06 14:00 UTC, merged